# Generated by Django 4.2.3 on 2023-07-11 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('matriculas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Convenio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('escolas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matriculas.escola')),
                ('matriculas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matriculas.matricula')),
            ],
            options={
                'db_table': 'convenios',
            },
        ),
    ]
