# Generated by Django 4.2.3 on 2023-07-08 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'alunos',
            },
        ),
        migrations.CreateModel(
            name='Escola',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('tipo', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'escolas',
            },
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('numero_de_matricula', models.AutoField(primary_key=True, serialize=False)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matriculas.aluno')),
                ('escola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matriculas.escola')),
            ],
            options={
                'db_table': 'matriculas',
            },
        ),
    ]
